-- =============================================================================
-- 003_db_generated_ids.sql
-- Northern Water Company Ltd — OASIS Springs
--
-- Fixes silent loss of sales (and payments) caused by CLIENT-generated keys.
--
-- Background
-- ----------
-- The app computed sales.id / payments.id on the client as
--   Math.max(visible rows) + 1
-- Since the role-based fetch refactor (commit 8baa7a4, 2026-06-12), a sales-role
-- user only loads the rows their RLS policy allows — their own location. So the
-- client-side max id is BELOW the true global max, and the generated id collided
-- with an existing row at another location. PostgREST returned that collision as
-- an error which the app ignored, so the INSERT was rejected silently: the sale
-- showed on the rep's screen (added to state optimistically) but was never
-- persisted. Observed missing in production for 2026-06-14 and 2026-06-16; the
-- 17th happened to land on free ids and saved.
--
-- This migration moves id and invoice-number generation into the database, so an
-- RLS-filtered client can never produce a colliding value. The app code is being
-- updated in the same change to stop sending id / invoiceNumber and to read the
-- DB-assigned values back via .select().
--
-- No RLS policy changes. INSERT policies already allow any authenticated user;
-- this only changes HOW id / invoiceNumber are produced.
--
-- Apply via the Supabase SQL Editor AFTER review. Safe to run once.
-- =============================================================================

begin;

-- ---------------------------------------------------------------------------
-- 1. sales.id -> GENERATED BY DEFAULT AS IDENTITY
--    BY DEFAULT (not ALWAYS): an explicitly supplied id still works, but an
--    omitted id is assigned from the sequence.
--
--    NOTE: this assumes sales.id is currently a plain integer/bigint PK with no
--    default. If it errors with "column ... already has a default", the column
--    is already serial/identity — in that case skip this ALTER and run only the
--    setval below to advance the sequence past max(id).
-- ---------------------------------------------------------------------------
alter table public.sales
  alter column id add generated by default as identity;

select setval(
  pg_get_serial_sequence('public.sales', 'id'),
  coalesce((select max(id) from public.sales), 0) + 1,
  false
);

-- ---------------------------------------------------------------------------
-- 2. payments.id -> GENERATED BY DEFAULT AS IDENTITY
-- ---------------------------------------------------------------------------
alter table public.payments
  alter column id add generated by default as identity;

select setval(
  pg_get_serial_sequence('public.payments', 'id'),
  coalesce((select max(id) from public.payments), 0) + 1,
  false
);

-- ---------------------------------------------------------------------------
-- 3. sales."invoiceNumber" -> database default from a dedicated sequence.
--    Format preserved: INV-001, INV-002, ... (to_char FM000 = min 3 digits,
--    grows beyond 3 without truncating — matches the old padStart(3,'0')).
-- ---------------------------------------------------------------------------
create sequence if not exists public.sales_invoice_seq;

-- Start the sequence above the highest existing invoice number. Existing values
-- look like 'INV-001'; strip non-digits and take the max.
select setval(
  'public.sales_invoice_seq',
  coalesce(
    (select max(nullif(regexp_replace("invoiceNumber", '\D', '', 'g'), '')::int)
     from public.sales),
    0
  ) + 1,
  false
);

alter table public.sales
  alter column "invoiceNumber"
  set default 'INV-' || to_char(nextval('public.sales_invoice_seq'), 'FM000');

commit;

-- =============================================================================
-- After applying, verify:
--   select max(id) from public.sales;
--   select nextval(pg_get_serial_sequence('public.sales','id'));   -- should be max+1
--   insert into public.sales ("customerId", date, items, total, paid, status,
--                             created_by)
--     values (<any valid customer>, current_date, '[]'::jsonb, 0, 0, 'pending', auth.uid())
--     returning id, "invoiceNumber";                               -- DB fills both
--   -- then delete that test row.
--
-- Still client-generated and carrying the SAME latent risk for any RLS-filtered
-- role (convert the same way when next touched):
--   customers.id, expenses.id, production_logs.id, purchases.id,
--   payroll_payments.id, stock_adjustments.id
-- =============================================================================
