-- =============================================================================
-- 004_db_generated_ids_production_purchases.sql
-- Northern Water Company Ltd — OASIS Springs
--
-- Moves id generation for production_logs and purchases into the database.
--
-- Background
-- ----------
-- 003_db_generated_ids.sql fixed sales/payments, and its closing note flagged
-- production_logs.id and purchases.id as still client-generated and carrying the
-- SAME latent risk, to be converted "the same way when next touched".
--
-- The application code (handleSaveProduction / handleSavePurchase) has since been
-- changed to STOP sending an id and to read the DB-assigned value back via
-- .select().single() — exactly like sales. If these columns are NOT yet identity
-- columns in the live database, those inserts fail with a NOT NULL violation and
-- production logs / purchases cannot be recorded at all (and, by design, stock is
-- left unchanged). This migration supplies the missing database half so the
-- already-deployed code works and can never produce a colliding id.
--
-- No RLS policy changes. INSERT policies already allow authenticated users;
-- this only changes HOW id is produced.
--
-- Apply via the Supabase SQL Editor AFTER review. Safe to run once.
-- =============================================================================

begin;

-- ---------------------------------------------------------------------------
-- 1. production_logs.id -> GENERATED BY DEFAULT AS IDENTITY
--    BY DEFAULT (not ALWAYS): an explicitly supplied id still works, but an
--    omitted id is assigned from the sequence.
--
--    NOTE: this assumes production_logs.id is currently a plain integer/bigint
--    PK with no default. If it errors with "column ... already has a default",
--    the column is already serial/identity — skip this ALTER and run only the
--    setval below to advance the sequence past max(id).
-- ---------------------------------------------------------------------------
alter table public.production_logs
  alter column id add generated by default as identity;

select setval(
  pg_get_serial_sequence('public.production_logs', 'id'),
  coalesce((select max(id) from public.production_logs), 0) + 1,
  false
);

-- ---------------------------------------------------------------------------
-- 2. purchases.id -> GENERATED BY DEFAULT AS IDENTITY
-- ---------------------------------------------------------------------------
alter table public.purchases
  alter column id add generated by default as identity;

select setval(
  pg_get_serial_sequence('public.purchases', 'id'),
  coalesce((select max(id) from public.purchases), 0) + 1,
  false
);

commit;

-- =============================================================================
-- After applying, verify:
--   select max(id) from public.production_logs;
--   select nextval(pg_get_serial_sequence('public.production_logs','id')); -- max+1
--   select max(id) from public.purchases;
--   select nextval(pg_get_serial_sequence('public.purchases','id'));       -- max+1
--
-- Still client-generated and carrying the SAME latent risk for any RLS-filtered
-- role (convert the same way when next touched):
--   customers.id, expenses.id, payroll_payments.id
-- (stock_adjustments already omits id on insert and relies on a DB default.)
-- =============================================================================
