-- =============================================================================
-- 004_production_logs_identity.sql
-- Northern Water Company Ltd — OASIS Springs
--
-- Same fix as migration 003, applied to production_logs: move id generation
-- into the database so the client never computes a colliding primary key.
--
-- production_logs is admin/manager only with no location filter, so it doesn't
-- hit the RLS-subset collision that affected sales. The risks here are:
--   * concurrent inserts from two devices/managers computing the same id, and
--   * a silently-rejected insert leaving inventory deducted/added (which
--     auto-persists) with no production record behind it — a BOM integrity gap.
-- The app code is updated in the same change to stop sending id, read the
-- DB-assigned id back via .select(), and apply inventory changes only on a
-- confirmed save.
--
-- No RLS policy changes. Apply via the Supabase SQL Editor AFTER review.
-- =============================================================================

begin;

-- production_logs.id -> GENERATED BY DEFAULT AS IDENTITY
-- BY DEFAULT (not ALWAYS): an explicitly supplied id still works, but an
-- omitted id is assigned from the sequence.
--
-- NOTE: assumes production_logs.id is a plain integer/bigint PK with no default.
-- If it errors with "column ... already has a default", the column is already
-- serial/identity — skip this ALTER and run only the setval below.
alter table public.production_logs
  alter column id add generated by default as identity;

select setval(
  pg_get_serial_sequence('public.production_logs', 'id'),
  coalesce((select max(id) from public.production_logs), 0) + 1,
  false
);

commit;

-- =============================================================================
-- Still client-generated and carrying the same latent risk (convert when next
-- touched): customers.id, expenses.id, purchases.id, payroll_payments.id,
-- stock_adjustments.id
-- =============================================================================
