-- =============================================================================
-- 004a_production_logs_identity.sql
-- Northern Water Company Ltd — OASIS Springs
--
-- HISTORICAL — SUPERSEDED BY 004b. Kept as the record of what was actually
-- applied on 2026-06-29. 004b redoes this same conversion idempotently and also
-- covers purchases; on a fresh database, running 004b alone is sufficient. This
-- file was renamed from `004_production_logs_identity.sql` (it shared the number
-- 004 with what is now 004b — see migrations/README.md).
--
-- Same fix as migration 003, applied to production_logs: move id generation
-- into the database so the client never computes a colliding primary key.
--
-- production_logs is admin/manager only with no location filter, so it doesn't
-- hit the RLS-subset collision that affected sales. The risks here are:
--   * concurrent inserts from two devices/managers computing the same id, and
--   * a silently-rejected insert leaving inventory deducted/added (which
--     auto-persists) with no production record behind it — a BOM integrity gap.
-- The app code is updated in the same change to stop sending id, read the
-- DB-assigned id back via .select(), and apply inventory changes only on a
-- confirmed save.
--
-- No RLS policy changes. Apply via the Supabase SQL Editor AFTER review.
-- =============================================================================

begin;

-- production_logs.id -> GENERATED BY DEFAULT AS IDENTITY
-- BY DEFAULT (not ALWAYS): an explicitly supplied id still works, but an
-- omitted id is assigned from the sequence.
--
-- The ALTER is guarded so this file is safe to re-run (it was a bare ALTER when
-- first applied, and errored with "column ... already has a default" if repeated).
-- attidentity is '' when the column is NOT an identity column, 'd' for GENERATED
-- BY DEFAULT, 'a' for GENERATED ALWAYS — so only ALTER when ''.
do $$
begin
  if (select attidentity from pg_attribute
      where attrelid = 'public.production_logs'::regclass and attname = 'id') = '' then
    alter table public.production_logs alter column id add generated by default as identity;
  end if;
end $$;

select setval(
  pg_get_serial_sequence('public.production_logs', 'id'),
  coalesce((select max(id) from public.production_logs), 0) + 1,
  false
);

commit;

-- =============================================================================
-- Still client-generated and carrying the same latent risk (convert when next
-- touched): customers.id, expenses.id, purchases.id, payroll_payments.id,
-- stock_adjustments.id
-- =============================================================================
