-- =============================================================================
-- 004b_db_generated_ids_production_purchases.sql
-- Northern Water Company Ltd — OASIS Springs
--
-- Renamed from `004_db_generated_ids_production_purchases.sql`: it shared the
-- number 004 with what is now 004a, which made filename order ambiguous for
-- anyone applying these in sequence. This file SUPERSEDES 004a and is the one to
-- run on a fresh database. Note it was actually applied AFTER 005 — see
-- migrations/README.md for the true chronology.
--
-- Moves id generation for production_logs and purchases into the database.
--
-- Background
-- ----------
-- 003_db_generated_ids.sql fixed sales/payments, and its closing note flagged
-- production_logs.id and purchases.id as still client-generated and carrying the
-- SAME latent risk, to be converted "the same way when next touched".
--
-- The application code (handleSaveProduction / handleSavePurchase) has since been
-- changed to STOP sending an id and to read the DB-assigned value back via
-- .select().single() — exactly like sales. If these columns are NOT yet identity
-- columns in the live database, those inserts fail with a NOT NULL violation and
-- production logs / purchases cannot be recorded at all (and, by design, stock is
-- left unchanged). This migration supplies the missing database half so the
-- already-deployed code works and can never produce a colliding id.
--
-- Idempotent: each column is converted only if it is not already an identity
-- column (production_logs.id was found to be identity already when this was first
-- applied), and the sequences are always re-synced past the current max. Safe to
-- re-run.
--
-- No RLS policy changes. INSERT policies already allow authenticated users;
-- this only changes HOW id is produced.
--
-- Apply via the Supabase SQL Editor AFTER review.
-- =============================================================================

begin;

-- ---------------------------------------------------------------------------
-- 1. production_logs.id -> GENERATED BY DEFAULT AS IDENTITY (if not already)
--    attidentity is '' when the column is NOT an identity column, 'd' for
--    GENERATED BY DEFAULT, 'a' for GENERATED ALWAYS. Only ALTER when ''.
-- ---------------------------------------------------------------------------
do $$
begin
  if (select attidentity from pg_attribute
      where attrelid = 'public.production_logs'::regclass and attname = 'id') = '' then
    alter table public.production_logs alter column id add generated by default as identity;
  end if;
end $$;

select setval(
  pg_get_serial_sequence('public.production_logs', 'id'),
  coalesce((select max(id) from public.production_logs), 0) + 1,
  false
);

-- ---------------------------------------------------------------------------
-- 2. purchases.id -> GENERATED BY DEFAULT AS IDENTITY (if not already)
-- ---------------------------------------------------------------------------
do $$
begin
  if (select attidentity from pg_attribute
      where attrelid = 'public.purchases'::regclass and attname = 'id') = '' then
    alter table public.purchases alter column id add generated by default as identity;
  end if;
end $$;

select setval(
  pg_get_serial_sequence('public.purchases', 'id'),
  coalesce((select max(id) from public.purchases), 0) + 1,
  false
);

commit;

-- =============================================================================
-- After applying, verify:
--   select max(id) from public.production_logs;
--   select nextval(pg_get_serial_sequence('public.production_logs','id')); -- max+1
--   select max(id) from public.purchases;
--   select nextval(pg_get_serial_sequence('public.purchases','id'));       -- max+1
--
-- Still client-generated and carrying the SAME latent risk for any RLS-filtered
-- role (convert the same way when next touched):
--   customers.id, expenses.id, payroll_payments.id
-- (stock_adjustments already omits id on insert and relies on a DB default.)
-- =============================================================================
