-- =============================================================================
-- 005_customers_expenses_purchases_identity.sql
-- Northern Water Company Ltd — OASIS Springs
--
-- Completes the move of primary-key generation into the database (after 003 for
-- sales/payments and 004 for production_logs). Converts the last three tables
-- that the client still generated ids for: customers, expenses, purchases.
--
-- customers is the high-risk one: a sales-role user only loads their own
-- location's customers (RLS), so the old client-side max(id)+1 could collide
-- with a customer at another location and the insert was silently rejected —
-- exactly the failure mode that lost sales. expenses/purchases are admin/manager
-- only (no RLS subset) so they were only exposed to concurrent-insert collisions
-- and silent failures, but are converted here for consistency and safety.
--
-- The app code is updated in the same change: every insert omits id, reads the
-- DB-assigned id back via .select(), applies local state / inventory only on a
-- confirmed save, and alerts on failure. Payroll expense inserts now link
-- payroll_payments.expense_id / production_logs.casual_expense_id to the
-- DB-assigned expense id.
--
-- employees, payroll_payments and stock_adjustments already use DB-generated
-- ids (the app already inserts them without an id), so they are NOT touched.
--
-- No RLS policy changes. Apply via the Supabase SQL Editor AFTER review.
-- =============================================================================

begin;

-- Each ALTER below is guarded so this file is safe to re-run. They were bare
-- ALTERs when first applied, which errored with "column ... already has a
-- default" on a second run — and purchases.id is converted BOTH here and in 004b,
-- so on a fresh in-order apply one of the two was always going to hit that error.
-- attidentity is '' when the column is NOT an identity column, 'd' for GENERATED
-- BY DEFAULT, 'a' for GENERATED ALWAYS — so only ALTER when ''.
-- The setvals are unguarded on purpose: re-syncing a sequence past max(id) is
-- already idempotent.

-- customers.id -> GENERATED BY DEFAULT AS IDENTITY
do $$
begin
  if (select attidentity from pg_attribute
      where attrelid = 'public.customers'::regclass and attname = 'id') = '' then
    alter table public.customers alter column id add generated by default as identity;
  end if;
end $$;
select setval(
  pg_get_serial_sequence('public.customers', 'id'),
  coalesce((select max(id) from public.customers), 0) + 1,
  false
);

-- expenses.id -> GENERATED BY DEFAULT AS IDENTITY
do $$
begin
  if (select attidentity from pg_attribute
      where attrelid = 'public.expenses'::regclass and attname = 'id') = '' then
    alter table public.expenses alter column id add generated by default as identity;
  end if;
end $$;
select setval(
  pg_get_serial_sequence('public.expenses', 'id'),
  coalesce((select max(id) from public.expenses), 0) + 1,
  false
);

-- purchases.id -> GENERATED BY DEFAULT AS IDENTITY
-- Also converted in 004b; whichever runs second is now a no-op instead of an error.
do $$
begin
  if (select attidentity from pg_attribute
      where attrelid = 'public.purchases'::regclass and attname = 'id') = '' then
    alter table public.purchases alter column id add generated by default as identity;
  end if;
end $$;
select setval(
  pg_get_serial_sequence('public.purchases', 'id'),
  coalesce((select max(id) from public.purchases), 0) + 1,
  false
);

commit;

-- =============================================================================
-- After this migration + 003 + 004, NO client-inserted table relies on a
-- client-generated primary key. All ids are DB-assigned.
-- =============================================================================
