-- =============================================================================
-- 005_customers_expenses_purchases_identity.sql
-- Northern Water Company Ltd — OASIS Springs
--
-- Completes the move of primary-key generation into the database (after 003 for
-- sales/payments and 004 for production_logs). Converts the last three tables
-- that the client still generated ids for: customers, expenses, purchases.
--
-- customers is the high-risk one: a sales-role user only loads their own
-- location's customers (RLS), so the old client-side max(id)+1 could collide
-- with a customer at another location and the insert was silently rejected —
-- exactly the failure mode that lost sales. expenses/purchases are admin/manager
-- only (no RLS subset) so they were only exposed to concurrent-insert collisions
-- and silent failures, but are converted here for consistency and safety.
--
-- The app code is updated in the same change: every insert omits id, reads the
-- DB-assigned id back via .select(), applies local state / inventory only on a
-- confirmed save, and alerts on failure. Payroll expense inserts now link
-- payroll_payments.expense_id / production_logs.casual_expense_id to the
-- DB-assigned expense id.
--
-- employees, payroll_payments and stock_adjustments already use DB-generated
-- ids (the app already inserts them without an id), so they are NOT touched.
--
-- No RLS policy changes. Apply via the Supabase SQL Editor AFTER review.
-- =============================================================================

begin;

-- customers.id -> GENERATED BY DEFAULT AS IDENTITY
-- NOTE (applies to all three below): assumes the column is a plain
-- integer/bigint PK with no default. If an ALTER errors with "column ... already
-- has a default", that table is already serial/identity — skip its ALTER and run
-- only its setval to advance the sequence past max(id).
alter table public.customers
  alter column id add generated by default as identity;
select setval(
  pg_get_serial_sequence('public.customers', 'id'),
  coalesce((select max(id) from public.customers), 0) + 1,
  false
);

-- expenses.id -> GENERATED BY DEFAULT AS IDENTITY
alter table public.expenses
  alter column id add generated by default as identity;
select setval(
  pg_get_serial_sequence('public.expenses', 'id'),
  coalesce((select max(id) from public.expenses), 0) + 1,
  false
);

-- purchases.id -> GENERATED BY DEFAULT AS IDENTITY
alter table public.purchases
  alter column id add generated by default as identity;
select setval(
  pg_get_serial_sequence('public.purchases', 'id'),
  coalesce((select max(id) from public.purchases), 0) + 1,
  false
);

commit;

-- =============================================================================
-- After this migration + 003 + 004, NO client-inserted table relies on a
-- client-generated primary key. All ids are DB-assigned.
-- =============================================================================
